import { Component, signal } from "@angular/core";
import { CommonModule } from "@angular/common";

@Component({
  selector: "app-terms-disclaimer",
  standalone: true,
  imports: [CommonModule],
  template: `
    <!-- Modal overlay -->
    <div class="modal-overlay" *ngIf="isOpen()" (click)="close()"></div>

    <!-- Modal -->
    <div class="modal" *ngIf="isOpen()">
      <div class="modal-content">
        <!-- Close button -->
        <button class="modal-close" (click)="close()" aria-label="Close">✕</button>

        <!-- Header -->
        <div class="modal-header">
          <h2>Terms of Use & Disclaimer</h2>
          <p class="modal-subtitle">Please read before using Tubreeze</p>
        </div>

        <!-- Tabs -->
        <div class="modal-tabs">
          <button
            class="tab-btn"
            [class.active]="activeTab() === 'terms'"
            (click)="activeTab.set('terms')"
          >
            Terms of Use
          </button>
          <button
            class="tab-btn"
            [class.active]="activeTab() === 'disclaimer'"
            (click)="activeTab.set('disclaimer')"
          >
            Disclaimer
          </button>
        </div>

        <!-- Content -->
        <div class="modal-body">
          <!-- TERMS OF USE TAB -->
          <div class="tab-pane" *ngIf="activeTab() === 'terms'">
            <h3>Acceptance of Terms</h3>
            <p>By using Tubreeze, you agree to these Terms of Use. If you do not agree, please do not use the service.</p>

            <h3>User Responsibilities</h3>
            <ul>
              <li>You must only submit YouTube URLs that you have rights or permission to process.</li>
              <li>You must not attempt to bypass YouTube's Terms of Service using this app.</li>
              <li>Commercial use is prohibited unless explicitly permitted in writing.</li>
              <li>You agree not to use this service for illegal, harmful, or unauthorized purposes.</li>
            </ul>

            <h3>API Key Usage</h3>
            <p><strong>Bring Your Own Key (BYOK):</strong> If you provide your own OpenAI API key, you are solely responsible for your API billing and usage charges.</p>
            <p>Your API key is never stored, logged, or transmitted to our servers beyond the current request. Keys are processed in-memory only.</p>

            <h3>Rate Limits & Fair Use</h3>
            <p>Tubreeze enforces fair-use rate limits. Automated scraping, mass processing, or excessive requests are prohibited. Violations may result in temporary or permanent service suspension.</p>

            <h3>Prohibited Uses</h3>
            <p>You may not use Tubreeze for:</p>
            <ul>
              <li>Illegal activities or copyright infringement</li>
              <li>Mass automation or scraping</li>
              <li>Circumventing YouTube's content policies</li>
              <li>Distributing copyrighted content without authorization</li>
              <li>Harmful, abusive, or harassing purposes</li>
            </ul>

            <h3>Content Processing</h3>
            <p>Tubreeze processes video transcripts temporarily during your request only. We do not store, archive, or retain full transcripts, audio, or video content after processing. Generated summaries may be displayed in your session but are not permanently retained by our service.</p>

            <h3>Third-Party Services</h3>
            <p>This service integrates with:</p>
            <ul>
              <li><strong>YouTube</strong> — for video content and metadata</li>
              <li><strong>OpenAI</strong> — for AI-powered summarization</li>
              <li><strong>Supadata</strong> — for transcript extraction</li>
            </ul>
            <p>We are not responsible for outages, changes, or discontinuations of these third-party services.</p>

            <h3>No Guarantee of Accuracy</h3>
            <p>Summaries, fluff ratings, and clickbait accuracy scores are generated by AI and may contain errors, omissions, or inaccuracies. You should verify important information independently.</p>

            <h3>Limitation of Liability</h3>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, TUBREEZE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND. WE DISCLAIM ALL IMPLIED WARRANTIES, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. IN NO EVENT SHALL WE BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THIS SERVICE.</p>

            <h3>Right to Modify or Discontinue</h3>
            <p>We reserve the right to modify, suspend, or discontinue Tubreeze at any time, with or without notice. We are not liable for any interruption or loss of service.</p>

            <h3>Governing Law</h3>
            <p>These Terms of Use are governed by and construed in accordance with applicable law. Any disputes shall be resolved in the appropriate jurisdiction.</p>
          </div>

          <!-- DISCLAIMER TAB -->
          <div class="tab-pane" *ngIf="activeTab() === 'disclaimer'">
            <h3>No Affiliation</h3>
            <p>Tubreeze is an independent service and is <strong>not affiliated with, endorsed by, or associated with YouTube, Google, OpenAI, or Supadata</strong>.</p>

            <h3>Not Responsible For</h3>
            <ul>
              <li><strong>Copyright Issues:</strong> You are responsible for ensuring you have the right to summarize or process any video content.</li>
              <li><strong>Incorrect Summaries:</strong> AI-generated summaries may contain errors or omissions. Always verify important information.</li>
              <li><strong>API Downtime:</strong> We are not responsible for outages caused by YouTube, OpenAI, Supadata, or other external services.</li>
              <li><strong>Billing Errors:</strong> If you provide your own API key, you are responsible for monitoring and controlling your own API costs.</li>
            </ul>

            <h3>Purpose</h3>
            <p>Tubreeze is designed for informational and educational purposes only. It is not intended for commercial use, legal advice, financial analysis, or any critical decision-making without independent verification.</p>

            <h3>Output May Contain Errors</h3>
            <p>Generated content, including summaries, scores, and suggestions, may be inaccurate, incomplete, or misleading. Use this tool as a starting point for research, not as a definitive source of information.</p>

            <h3>User Responsibility</h3>
            <p>You assume full responsibility and liability for what you do with any content generated by Tubreeze. We are not liable for misuse, misinterpretation, or consequences arising from the use of generated summaries or scores.</p>

            <h3>Data Handling</h3>
            <ul>
              <li><strong>No Permanent Storage:</strong> Audio, video, and transcript data are processed temporarily and deleted immediately after your request completes.</li>
              <li><strong>No API Key Storage:</strong> If you provide your own API keys, they are never saved to our servers and exist only in-memory during processing.</li>
              <li><strong>No Tracking:</strong> We do not store, log, or track individual user summarization requests or personal data beyond basic service operation.</li>
            </ul>

            <h3>Updates to This Disclaimer</h3>
            <p>We may update this disclaimer at any time. Continued use of Tubreeze constitutes acceptance of the updated terms.</p>
          </div>
        </div>

        <!-- Footer -->
        <div class="modal-footer">
          <button class="btn-primary" (click)="close()">I Understand & Accept</button>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .modal-overlay {
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background: rgba(0, 0, 0, 0.6);
      z-index: 999;
      animation: fadeIn 0.2s ease-out;
    }

    @keyframes fadeIn {
      from { opacity: 0; }
      to { opacity: 1; }
    }

    .modal {
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      background: var(--color-surface-1);
      border-radius: 12px;
      border: 1px solid rgba(255,255,255,0.05);
      box-shadow: 0 20px 60px rgba(0,0,0,0.7);
      z-index: 1000;
      max-width: 600px;
      width: 90%;
      max-height: 85vh;
      display: flex;
      flex-direction: column;
      animation: slideUp 0.3s ease-out;
    }

    @keyframes slideUp {
      from {
        opacity: 0;
        transform: translate(-50%, -40%);
      }
      to {
        opacity: 1;
        transform: translate(-50%, -50%);
      }
    }

    .modal-close {
      position: absolute;
      top: 16px;
      right: 16px;
      background: transparent;
      border: none;
      color: var(--text-primary);
      font-size: 24px;
      cursor: pointer;
      padding: 4px 8px;
      display: flex;
      align-items: center;
      justify-content: center;
      z-index: 1001;
    }

    .modal-close:hover {
      opacity: 0.7;
    }

    .modal-header {
      padding: 24px 24px 12px;
      border-bottom: 1px solid rgba(255,255,255,0.03);
    }

    .modal-header h2 {
      margin: 0 0 4px;
      font-size: 20px;
      font-weight: 700;
      color: var(--text-primary);
    }

    .modal-subtitle {
      margin: 0;
      font-size: 13px;
      color: var(--text-secondary);
    }

    .modal-tabs {
      display: flex;
      gap: 0;
      border-bottom: 1px solid rgba(255,255,255,0.03);
      padding: 0;
    }

    .tab-btn {
      flex: 1;
      background: transparent;
      border: none;
      color: var(--text-secondary);
      padding: 12px 16px;
      cursor: pointer;
      font-size: 13px;
      font-weight: 600;
      border-bottom: 2px solid transparent;
      transition: all 0.2s;
    }

    .tab-btn:hover {
      color: var(--text-primary);
      background: rgba(255,255,255,0.01);
    }

    .tab-btn.active {
      color: var(--color-primary);
      border-bottom-color: var(--color-primary);
    }

    .modal-body {
      flex: 1;
      overflow-y: auto;
      padding: 20px 24px;
      font-size: 13px;
      line-height: 1.6;
      color: var(--text-primary);
    }

    .tab-pane h3 {
      margin: 16px 0 8px;
      font-size: 14px;
      font-weight: 700;
      color: var(--color-accent);
      text-transform: uppercase;
      letter-spacing: 0.3px;
    }

    .tab-pane h3:first-child {
      margin-top: 0;
    }

    .tab-pane p {
      margin: 0 0 12px;
      text-align: left;
    }

    .tab-pane ul {
      margin: 0 0 12px 18px;
      padding: 0;
    }

    .tab-pane li {
      margin-bottom: 6px;
      color: var(--text-secondary);
    }

    .modal-footer {
      padding: 16px 24px 24px;
      border-top: 1px solid rgba(255,255,255,0.03);
      display: flex;
      gap: 12px;
      justify-content: flex-end;
    }

    .btn-primary {
      background: linear-gradient(90deg, var(--color-primary), var(--color-primary-700));
      border: none;
      color: #ffffff;
      padding: 10px 20px;
      border-radius: 8px;
      font-weight: 600;
      cursor: pointer;
      font-size: 13px;
      transition: transform 0.2s;
    }

    .btn-primary:hover {
      transform: translateY(-1px);
    }

    /* Scrollbar styling */
    .modal-body::-webkit-scrollbar {
      width: 6px;
    }

    .modal-body::-webkit-scrollbar-track {
      background: transparent;
    }

    .modal-body::-webkit-scrollbar-thumb {
      background: rgba(255,255,255,0.1);
      border-radius: 3px;
    }

    .modal-body::-webkit-scrollbar-thumb:hover {
      background: rgba(255,255,255,0.2);
    }

    @media (max-width: 600px) {
      .modal {
        width: 95%;
        max-height: 90vh;
      }

      .modal-header {
        padding: 20px 16px 12px;
      }

      .modal-body {
        padding: 16px;
      }

      .modal-footer {
        padding: 12px 16px 16px;
      }
    }
  `],
})
export class TermsDisclaimerComponent {
  isOpen = signal(false);
  activeTab = signal<"terms" | "disclaimer">("terms");

  open() {
    this.isOpen.set(true);
  }

  close() {
    this.isOpen.set(false);
  }
}
